# Generated by Django 4.0.6 on 2022-07-22 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_post_vote_up_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote_up',
            field=models.ManyToManyField(related_name='post_vote_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
